### ISSUE TITLE
Clicking with multiparts

### ISSUE THREAD

**Issue by adrwa** [amadornes/MCMultiPart#125] opened 2018-04-04 23:02 UTC
When right clicking with a block that has had a stack wrapper applied, there are two issues

1. ~~If MCMP thinks the block can be placed, it'll place the block without asking the clicked block about onBlockActivated~~

2. Clicking with a multipart but cant be placed will trigger onBlockActivated, but if the activation is successful, there is no item animation for clicking

**Comment by dblsaiko** [comment] 2018-04-05 10:18
Duplicate of #73 I guess?

**Comment by adrwa** [comment] 2018-04-05 10:49
Whoops i didnt see that, number 2 isnt mentioned in that issue so only the first part is a duplicate as far as i can see

**Closed as completed** 2018-04-25 20:11 UTC
Labels: bug
