### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Dyonovan** [amadornes/MCMultiPart#17] opened 2016-03-02 12:48 UTC
http://pastebin.com/YKGaSeLT

https://github.com/TeamBR-Modding/NeoTech/issues/190

**Comment by amadornes** [comment] 2016-03-02 14:51
Hmm... Looks like somebody's trying to access the multipart model without calling handleBlockState().
I wasn't really expecting this to happen, but it should be really easy to fix. Working on it!

**Comment by amadornes** [comment] 2016-03-02 15:10
Should be fixed now :)

**Closed as completed by amadornes** 2016-03-02 15:10 UTC

**Comment by pauljoda** [comment] 2016-03-02 18:42
Just an input based on what I've seen, the mod ArchitectureCraft has its own block render dispatcher that seems to be really bad. Its calling methods on models it shouldn't be. Its good you put in a catch, but just know the issue is on their end
