### ISSUE TITLE
Crash upon Entering a Galacticraft Dimension

### ISSUE THREAD

**Issue by SirKillz** [amadornes/MCMultiPart#81] opened 2017-06-07 19:30 UTC
Mc Multipart 1.4.0
Every time I launch into a Galacticraft Dimension or return from one my server crashes and give the following error.   
https://pastebin.com/Ww7GCKft

**Comment by tomelfring** [comment] 2017-06-08 08:17
Duplicate of #71

**Comment by dblsaiko** [comment] 2017-12-23 23:23
Closing because this is an MCMP1 issue which has been outdated for a while. If this issue still occurs in MCMP2 (1.11+), please open a new issue.

**Closed as completed by dblsaiko** 2017-12-23 23:23 UTC
